dist: jammy

git:
  depth: 1

install:
- sudo apt-get install xsltproc
- git clone https://github.com/nakajima/tidy-html5 --branch pre-formatting --single-branch
- cd tidy-html5
- cd build/cmake
- cmake ../.. -DCMAKE_BUILD_TYPE=Release
- make
- sudo make install
- cd $TRAVIS_BUILD_DIR

language: python

os: linux

python: 3.13

script:
- tidy --version
