language: python

python: 3.6

install:
  - sudo apt-get install xsltproc
  - git clone -b issue-721 https://github.com/htacg/tidy-html5.git
  - cd tidy-html5
  - cd build/cmake
  - cmake ../.. -DCMAKE_BUILD_TYPE=Release
  - make
  - sudo make install

script:
  - echo "HTML Tidy installed!"
